plugins:
  - jekyll-seo-tag

title: Robin Wu
description: my personal website
theme: minima

header_pages:
  - about.md
  - project.md
  - interests.md
  - contact.md

author: Robin Wu   

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/eleveneigh" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/leyan-wu-36398b31a" }
    - { platform: email,   user_url: "mailto:lw403@duke.edu" }
