title: Robin Wu
description: my personal website
theme: minima
author:
  name: Robin Wu
  email: lw403@duke.edu
  github: eleveneigh
  linkedin: www.linkedin.com/in/leyan-wu-36398b31a

header_pages:
  - about.md
  - projects.md
  - contact.md
